/**
 * FORK-ONLY FILE — not present upstream, so it never conflicts on rebase.
 *
 * Thin client for the fork's own `/fork/*` endpoints.
 *
 * These endpoints are deliberately *not* added to the generated SDKs (`@opencode-ai/sdk`,
 * `@opencode-ai/client`): those are produced by codegen into checked-in `generated/` directories, and
 * regenerating them would rewrite thousands of lines that upstream also regenerates on every release
 * — the single worst rebase conflict this fork could create. A hand-written fetch wrapper costs a few
 * lines and keeps every generated file untouched.
 *
 * Auth and fetch come from the same places the real SDK uses, so behaviour matches on desktop, WSL
 * and remote servers alike.
 */
import type { ServerConnection } from "@/context/server"
import { authTokenFromCredentials } from "@/utils/server"

export type ForkConfigFile = {
  path: string
  content: string
  exists: boolean
}

export type ForkConfigWriteResult = { ok: true; path: string; content: string } | { ok: false; error: string }

export type ForkConfigValidation = {
  ok: boolean
  error?: string
}

/** JSON Schema document: root `$ref` into `$defs`, as produced by `Schema.toJsonSchemaDocument`. */
export type ForkConfigSchema = {
  $ref?: string
  $defs?: Record<string, JsonSchemaNode>
  [key: string]: unknown
}

export type JsonSchemaNode = {
  type?: string | string[]
  description?: string
  properties?: Record<string, JsonSchemaNode>
  additionalProperties?: boolean | JsonSchemaNode
  items?: JsonSchemaNode
  anyOf?: JsonSchemaNode[]
  oneOf?: JsonSchemaNode[]
  allOf?: JsonSchemaNode[]
  enum?: unknown[]
  const?: unknown
  $ref?: string
  [key: string]: unknown
}

export function createForkApi(input: { server: ServerConnection.HttpBase; fetch?: typeof globalThis.fetch }) {
  const doFetch = input.fetch ?? globalThis.fetch.bind(globalThis)
  const base = input.server.url.replace(/\/+$/, "")

  const buildHeaders = (hasBody: boolean) => {
    const headers: Record<string, string> = {}
    if (input.server.password) {
      headers.Authorization = `Basic ${authTokenFromCredentials({
        username: input.server.username,
        password: input.server.password,
      })}`
    }
    if (hasBody) headers["content-type"] = "application/json"
    return headers
  }

  async function call<T>(path: string, init?: { method?: string; body?: unknown }): Promise<T> {
    const response = await doFetch(`${base}${path}`, {
      method: init?.method ?? "GET",
      headers: buildHeaders(init?.body !== undefined),
      body: init?.body === undefined ? undefined : JSON.stringify(init.body),
    })
    if (!response.ok) {
      throw new Error(`${init?.method ?? "GET"} ${path} → ${response.status} ${response.statusText}`)
    }
    // Routed through `unknown` so the `any` from `response.json()` does not leak into callers. The
    // remaining `as T` is unavoidable for a generic fetch wrapper without validating every response
    // shape here; these four endpoints are this fork's own and are schema-checked server-side.
    const data: unknown = await response.json()
    return data as T
  }

  return {
    /** JSON Schema for the config file, generated by the server from its own compiled schema. */
    schema: () => call<ForkConfigSchema>("/fork/config/schema"),
    /** Verbatim contents of the server's global config file. */
    read: () => call<ForkConfigFile>("/fork/config/raw"),
    /** Dry run: same parse and schema decode a save performs, writing nothing. */
    validate: (content: string) =>
      call<ForkConfigValidation>("/fork/config/validate", { method: "POST", body: { content } }),
    /** Whole-file replace. Rejected without writing if the content would not load. */
    write: (content: string) => call<ForkConfigWriteResult>("/fork/config/raw", { method: "PUT", body: { content } }),
  }
}

export type ForkApi = ReturnType<typeof createForkApi>

/** Flattened schema entry for the reference panel. */
export type ConfigFieldDoc = {
  key: string
  type: string
  description?: string
}

function resolveRef(schema: ForkConfigSchema, ref: string): JsonSchemaNode | undefined {
  const match = /^#\/\$defs\/(.+)$/.exec(ref)
  if (!match) return undefined
  return schema.$defs?.[decodeURIComponent(match[1])]
}

/** Human-readable type label. Nullable unions collapse to the non-null member plus a `?` marker. */
function typeLabel(node: JsonSchemaNode | undefined, schema: ForkConfigSchema, depth = 0): string {
  if (!node || depth > 4) return "any"
  if (node.$ref) {
    const name = node.$ref.split("/").pop()
    const resolved = resolveRef(schema, node.$ref)
    // Prefer a structural label for wrappers; keep the definition name when it is meaningful.
    if (resolved?.enum) return resolved.enum.map((value) => JSON.stringify(value)).join(" | ")
    return name ? decodeURIComponent(name) : "object"
  }
  if (node.enum) return node.enum.map((value) => JSON.stringify(value)).join(" | ")
  if (node.const !== undefined) return JSON.stringify(node.const)

  const branches = node.anyOf ?? node.oneOf
  if (branches?.length) {
    const labels = branches
      .filter((branch) => !(branch.type === "null"))
      .map((branch) => typeLabel(branch, schema, depth + 1))
    const nullable = branches.some((branch) => branch.type === "null")
    const joined = [...new Set(labels)].join(" | ") || "any"
    return nullable ? `${joined} | null` : joined
  }

  if (node.type === "array") return `${typeLabel(node.items, schema, depth + 1)}[]`
  if (node.type === "object" || node.properties) {
    if (node.additionalProperties && typeof node.additionalProperties === "object") {
      return `record<string, ${typeLabel(node.additionalProperties, schema, depth + 1)}>`
    }
    return "object"
  }
  if (Array.isArray(node.type)) return node.type.join(" | ")
  return node.type ?? "any"
}

/**
 * Top-level config keys with type and description, for the reference panel.
 *
 * The root of the generated document is only a `$ref`, so the real object has to be resolved out of
 * `$defs` first — reading `schema.properties` directly finds nothing.
 */
export function configFieldDocs(schema: ForkConfigSchema | undefined): ConfigFieldDoc[] {
  if (!schema) return []
  const root = schema.$ref ? resolveRef(schema, schema.$ref) : (schema as JsonSchemaNode)
  const properties = root?.properties
  if (!properties) return []
  return Object.entries(properties)
    .filter(([key]) => key !== "$schema")
    .map(([key, node]) => ({
      key,
      type: typeLabel(node, schema),
      description: typeof node.description === "string" ? node.description : undefined,
    }))
    .sort((a, b) => a.key.localeCompare(b.key))
}
